#
# number_types.py
#

from ..constants.hold_registers import *

NUMBER_TYPES = [
    # --- System & Grid ---
    {
        "name": "Modbus Address",
        "register": H_COM_ADDRESS,
        "register_type": "hold",
        "min": 0,
        "max": 150,
        "step": 1,
        "unit": "",
        "multiplier": 1,
        "icon": "mdi:numeric",
        "enabled": False,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Grid Connect Time",
        "register": H_CONNECT_TIME,
        "register_type": "hold",
        "min": 30,
        "max": 600,
        "step": 1,
        "unit": "s",
        "multiplier": 1,
        "icon": "mdi:timer",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Grid",
        "multiplier": 1,
        "icon": "mdi:timer-sand",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Grid Reconnect Time",
        "register": H_RECONNECT_TIME,
        "register_type": "hold",
        "min": 0,
        "max": 900,
        "step": 1,
        "unit": "s",
        "multiplier": 1,
        "icon": "mdi:timer-refresh",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Grid",
    },
    {
        "name": "Grid Voltage Low Limit",
        "register": H_GRID_VOLT_CONN_LOW,
        "register_type": "hold",
        "min": 0.0,
        "max": 6553.5,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:arrow-collapse-vertical",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Grid",
    },
    {
        "name": "Grid Voltage High Limit",
        "register": H_GRID_VOLT_CONN_HIGH,
        "register_type": "hold",
        "min": 0.0,
        "max": 6553.5,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:arrow-expand-vertical",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Grid",
    },
    {
        "name": "Grid Frequency Low Limit",
        "register": H_GRID_FREQ_CONN_LOW,
        "register_type": "hold",
        "min": 0.00,
        "max": 655.35,
        "step": 0.01,
        "unit": "Hz",
        "multiplier": 100,
        "icon": "mdi:arrow-collapse-horizontal",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Grid",
    },
    {
        "name": "Grid Frequency High Limit",
        "register": H_GRID_FREQ_CONN_HIGH,
        "register_type": "hold",
        "min": 0.00,
        "max": 655.35,
        "step": 0.01,
        "unit": "Hz",
        "multiplier": 100,
        "icon": "mdi:arrow-expand-horizontal",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Grid",
    },
    {
        "name": "Max Grid Input Power",
        "register": H_MAX_GRID_INPUT_POWER,
        "register_type": "hold",
        "min": 0,
        "max": 65535,
        "step": 0.1,
        "unit": "kW",
        "multiplier": 10,
        "icon": "mdi:import",
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Start Discharge P_import",
        "register": H_PTOUSER_START_DISCHG_THRESHOLD,
        "register_type": "hold",
        "min": 0,
        "max": 65535,
        "step": 1,
        "unit": "W",
        "multiplier": 1,
        "icon": "mdi:import",
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Battery",
    },
    {
        "name": "External CT Power Offset",
        "register": H_WCT_POWER_OFFSET,
        "register_type": "hold",
        "min": -32768, # signed short int
        "max": 32767,
        "step": 1,
        "unit": "W",
        "multiplier": 1,
        "icon": "mdi:plus-minus-variant",
        "extract": lambda value: value if value < 32768 else value - 65536,  # Convert unsigned to signed
        "compose": lambda orig, value: value if value >= 0 else value + 65536,  # Convert signed to unsigned
        "enabled": True,
        "visible": True,
        "master_only": False,
    },

    # --- Power Control ---
    {
        "name": "Active Power Percent",
        "register": H_ACTIVE_POWER_PERCENT_CMD,
        "register_type": "hold",
        "min": 0,
        "max": 100,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:brightness-percent",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Power Soft Start Slope",
        "register": H_POWER_SOFT_START_SLOPE,
        "register_type": "hold",
        "min": 1,
        "max": 4000,
        "step": 1,
        "unit": "%/min",
        "multiplier": 1,
        "icon": "mdi:stairs-up",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Max Backflow Power",
        "register": H_MAX_BACKFLOW_POWER,
        "register_type": "hold",
        "min": 0,
        "max": 100,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:export",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },

    # --- Charging & Discharging ---
    {
        "name": "Charge Current",
        "register": H_CHARGE_CURRENT,
        "register_type": "hold",
        "min": 0,
        "max": 500,
        "step": 1,
        "unit": "A",
        "multiplier": 1,
        "icon": "mdi:current-ac",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Discharge Current",
        "register": H_DISCHARGE_CURRENT,
        "register_type": "hold",
        "min": 0,
        "max": 500,
        "step": 1,
        "unit": "A",
        "multiplier": 1,
        "icon": "mdi:current-ac",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "AC Charge Power",
        "register": H_AC_CHARGE_POWER_CMD,
        "register_type": "hold",
        "min": 0,
        "max": 25,
        "step": 1,
        "unit": "kW",
        "multiplier": 10,
        "icon": "mdi:battery-charging",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "AC Charge SOC Limit",
        "register": H_AC_CHARGE_SOC_LIMIT,
        "register_type": "hold",
        "min": 0,
        "max": 100,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:battery-charging-90",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "AC Charge Start Voltage",
        "register": H_AC_CHARGE_START_VOLT,
        "register_type": "hold",
        "min": 38.5,
        "max": 52.0,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:battery-arrow-up-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "AC Charge End Voltage",
        "register": H_AC_CHARGE_END_VOLT,
        "register_type": "hold",
        "min": 48.0,
        "max": 59.0,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:battery-check-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "AC Charge Start SOC",
        "register": H_AC_CHARGE_START_SOC,
        "register_type": "hold",
        "min": 0,
        "max": 90,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:battery-arrow-up-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "AC Charge End SOC",
        "register": H_AC_CHARGE_END_SOC,
        "register_type": "hold",
        "min": 0,
        "max": 100,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:battery-arrow-up-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "AC Charge Current from Grid",
        "register": H_AC_CHARGE_BAT_CURRENT,
        "register_type": "hold",
        "min": 0,
        "max": 140,
        "step": 1,
        "unit": "A",
        "multiplier": 1,
        "icon": "mdi:current-ac",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "On-Grid Cut-Off SOC",
        "register": H_EOD_SOC,
        "register_type": "hold",
        "min": 10,
        "max": 100,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:battery-low",
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Battery",
    },
    {
        "name": "On-Grid Cut-Off Voltage",
        "register": H_ONGRID_EOD_VOLTAGE,
        "register_type": "hold",
        "min": 40.0,
        "max": 56.0,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:grid",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Grid",
    },
    {
        "name": "Battery Stop Charging SOC",
        "register": H_BAT_STOP_CHARGE_SOC,
        "register_type": "hold",
        "min": 10,
        "max": 101,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:battery-off",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Battery Stop Charging Voltage",
        "register": H_BAT_STOP_CHARGE_VOLT,
        "register_type": "hold",
        "min": 40.0,
        "max": 59.5,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:battery-off-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Quick Charge Time",
        "register": H_QUICK_CHG_TIME,
        "register_type": "hold",
        "min": 0,
        "max": 65535,
        "step": 1,
        "unit": "m",
        "multiplier": 1,
        "icon": "mdi:timer",
        "enabled": True,
        "visible": True,
        "device_group": "Battery",
        "multiplier": 1,
        "icon": "mdi:timer-sand",
        "enabled": True,
        "visible": True,
        "master_only": False,
    },

    # --- EPS (Off-Grid) ---
    {
        "name": "Off-Grid Cut-Off SOC",
        "register": H_SOC_LOW_LIMIT_FOR_EPS_DISCHG,
        "register_type": "hold",
        "min": 0,
        "max": 100,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:battery-alert",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },

    # --- Unmatched/Lead-Acid Battery ---
    {
        "name": "Unmatched Battery Capacity",
        "register": H_BATTERY_CAPACITY,
        "register_type": "hold",
        "min": 0,
        "max": 10000,
        "step": 1,
        "unit": "Ah",
        "multiplier": 1,
        "icon": "mdi:battery",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Unmatched Battery Nominal Voltage",
        "register": H_BATTERY_NOMINAL_VOLTAGE,
        "register_type": "hold",
        "min": 40.0,
        "max": 59.0,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:battery",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Float Charge Voltage",
        "register": H_FLOAT_CHARGE_VOLT,
        "register_type": "hold",
        "min": 50.0,
        "max": 56.0,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:battery-plus-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Equalization Interval",
        "register": H_EQUALIZATION_INTERVAL,
        "register_type": "hold",
        "min": 0,
        "max": 365,
        "step": 1,
        "unit": "Days",
        "multiplier": 1,
        "icon": "mdi:calendar-sync",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Equalization Time",
        "register": H_EQUALIZATION_TIME,
        "register_type": "hold",
        "min": 0,
        "max": 24,
        "step": 1,
        "unit": "Hours",
        "multiplier": 1,
        "icon": "mdi:timer-cog",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Battery Low Voltage Alarm",
        "register": H_BAT_LOW_VOLTAGE_ALARM,
        "register_type": "hold",
        "min": 40.0,
        "max": 50.0,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:battery-alert-variant-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Battery Low Voltage Recovery",
        "register": H_BAT_LOW_BACK_VOLTAGE,
        "register_type": "hold",
        "min": 42.0,
        "max": 52.0,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:battery-sync-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Battery Low SOC Alarm",
        "register": H_BAT_LOW_SOC_ALARM,
        "register_type": "hold",
        "min": 0,
        "max": 90,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:battery-alert-variant-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Battery Low SOC Recovery",
        "register": H_BAT_LOW_BACK_SOC,
        "register_type": "hold",
        "min": 20,
        "max": 100,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:battery-sync-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Battery Calibration Period",
        "register": H_NO_FULL_CHG_DAY_CONFIG,
        "register_type": "hold",
        "extract": lambda value: (value >> 8) & 0xFF,
        "compose": lambda orig, value: (orig & 0x00FF) | ((value & 0xFF) << 8),
        "min": 0,
        "max": 255,
        "step": 1,
        "unit": "d",
        "multiplier": 1,
        "icon": "mdi:battery-sync-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },

    # --- Generator ---
    {
        "name": "Generator Rated Power",
        "register": H_GEN_RATED_POWER,
        "register_type": "hold",
        "min": 0,
        "max": 65535,
        "step": 1,
        "unit": "W",
        "multiplier": 1,
        "icon": "mdi:engine",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Generator",
    },
    {
        "name": "Generator Charge Start Voltage",
        "register": H_GEN_CHARGE_START_VOLT,
        "register_type": "hold",
        "min": 38.4,
        "max": 52.0,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:engine-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Generator Charge End Voltage",
        "register": H_GEN_CHARGE_END_VOLT,
        "register_type": "hold",
        "min": 48.0,
        "max": 59.0,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:engine-off-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Generator Charge Start SOC",
        "register": H_GEN_CHARGE_START_SOC,
        "register_type": "hold",
        "min": 0,
        "max": 90,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:engine-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Generator Charge End SOC",
        "register": H_GEN_CHARGE_END_SOC,
        "register_type": "hold",
        "min": 20,
        "max": 100,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:engine-off-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Max Generator Charge Current",
        "register": H_MAX_GEN_CHARGE_BAT_CURRENT,
        "register_type": "hold",
        "min": 0,
        "max": 4000,
        "step": 1,
        "unit": "A",
        "multiplier": 1,
        "icon": "mdi:engine",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },

    # --- Peak Shaving ---
    {
        "name": "Grid Peak Shaving Power",
        "register": H_GRID_PEAK_SHAVING_POWER,
        "register_type": "hold",
        "min": 0.0,
        "max": 25.5,
        "step": 0.1,
        "unit": "kW",
        "multiplier": 10,
        "icon": "mdi:chart-gantt",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Grid",
    },
    {
        "name": "Grid Peak Shaving SOC",
        "register": H_GRID_PEAK_SHAVING_SOC,
        "register_type": "hold",
        "min": 0,
        "max": 100,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:chart-gantt",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },

    # --- Miscellaneous ---
    {
        "name": "LCD Password",
        "register": H_LCD_PASSWORD,
        "register_type": "hold",
        "min": 0,
        "max": 65535,
        "step": 1,
        "unit": "",
        "multiplier": 1,
        "icon": "mdi:lock",
        "enabled": False,
        "visible": True,
        "master_only": True,
    },
    
    # --- New Number Entities from 2025-06-14 Documentation ---
    {
        "name": "Battery SOC Hysteresis",
        "register": H_DELTA_SOC,
        "register_type": "hold",
        "min": 0,
        "max": 100, # Assuming a reasonable range
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:percent-box-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Battery Voltage Hysteresis",
        "register": H_DELTA_VOLT,
        "register_type": "hold",
        "min": 2.0,
        "max": 10.0,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:volt-box-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "BUS Overvoltage Alarm Point",
        "register": H_BUS_VOLT_HIGH_SET,
        "register_type": "hold",
        "min": 550,
        "max": 595,
        "step": 1,
        "unit": "V",
        "multiplier": 1,
        "icon": "mdi:bus-alert",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Discharge Recovery SOC Threshold",
        "register": H_DISCHARGE_RECOVERY,
        "register_type": "hold",
        "min": 5, # As per documentation
        "max": 100, # Assuming a max of 100%
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:battery-sync-outline",
        "extract": lambda value: value & 0xFF,
        "compose": lambda orig, value: (orig & 0xFF00) | (value & 0xFF),
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Discharge Recovery Volt Threshold",
        "register": H_DISCHARGE_RECOVERY,
        "register_type": "hold",
        "min": 1.0, # As per documentation
        "max": 20.0, # Assuming a reasonable max
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:battery-sync-outline",
        "extract": lambda value: (value >> 8) & 0xFF,
        "compose": lambda orig, value: (orig & 0x00FF) | ((value & 0xFF) << 8),
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "WattNode CT1 Amps",
        "register": H_WATTNODE_CT_AMPS_1,
        "register_type": "hold",
        "min": 0,
        "max": 6000,
        "step": 1,
        "unit": "A",
        "multiplier": 1,
        "icon": "mdi:current-ac",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "WattNode CT2 Amps",
        "register": H_WATTNODE_CT_AMPS_2,
        "register_type": "hold",
        "min": 0,
        "max": 6000,
        "step": 1,
        "unit": "A",
        "multiplier": 1,
        "icon": "mdi:current-ac",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "WattNode CT3 Amps",
        "register": H_WATTNODE_CT_AMPS_3,
        "register_type": "hold",
        "min": 0,
        "max": 6000,
        "step": 1,
        "unit": "A",
        "multiplier": 1,
        "icon": "mdi:current-ac",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "NEC 120% Bus Bar Limit",
        "register": H_NEC_120_BUS_BAR_LIMIT,
        "register_type": "hold",
        "min": 5,
        "max": 80,
        "step": 1,
        "unit": "A",
        "multiplier": 1,
        "icon": "mdi:current-ac",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
]
